version: '3.3'

services:
  app:
    image: chess-server:latest
    environment:
      SECRET: ${SECRET}
      JWT_DOMAIN: ${JWT_DOMAIN}
      PUZZLES_DB_PATH: ${PUZZLES_DB_PATH}
    ports:
      - "8080:8080"
    restart: always
